SHELL = /bin/bash

build:
	make -C test build
	make -C test2 build
	make -C virtiogpu build

install:
	make -C test install
	make -C test2 install
	make -C virtiogpu install

clean:
	make -C test clean
	make -C test2 clean
	make -C virtiogpu clean