SHELL = /bin/bash

build:
	make -C init build
	make -C test build
	make -C test2 build
	make -C test3 build

install:
	make -C init install
	make -C test install
	make -C test2 install
	make -C test3 install

clean:
	make -C init clean
	make -C test clean
	make -C test2 clean
	make -C test3 clean